# Generated by Django 6.0.4 on 2026-05-15 12:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='structure',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='submission',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
